# Generated by Django 6.0.1 on 2026-02-05 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interventions', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='intervention',
            name='date_cloture',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='intervention',
            name='est_termine',
            field=models.BooleanField(default=False),
        ),
    ]
