# Generated by Django 6.0.1 on 2026-02-11 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilisateurs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='utilisateur',
            name='role',
            field=models.CharField(choices=[('utilisateur', 'Utilisateur'), ('technicien', 'Technicien'), ('admin', 'Administrateur')], default='utilisateur'),
        ),
    ]
