# Generated by Django 6.0.1 on 2026-02-11 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilisateurs', '0002_alter_utilisateur_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='utilisateur',
            name='role',
            field=models.CharField(choices=[('utilisateur', 'Utilisateur'), ('technicien', 'Technicien'), ('admin', 'Administrateur')], default='utilisateur', max_length=20),
        ),
    ]
