# Generated by Django 6.0.1 on 2026-02-04 14:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Etat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField()),
            ],
        ),
        migrations.CreateModel(
            name='TypeEquipement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField()),
            ],
        ),
        migrations.CreateModel(
            name='Equipement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField()),
                ('numero_serie', models.CharField()),
                ('date_achat', models.DateField(blank=True, null=True)),
                ('description', models.CharField()),
                ('etat', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Parcinfo.etat')),
                ('type_equipement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Parcinfo.typeequipement')),
            ],
        ),
    ]
