# Generated by Django 6.0.1 on 2026-02-04 14:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Parcinfo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TypeDemande',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField()),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField()),
                ('description', models.TextField()),
                ('statut', models.CharField(choices=[('ouvert', 'Ouvert'), ('en_cours', 'En_cours'), ('fermer', 'Fermer')], default='ouvert')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('equipement', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Parcinfo.equipement')),
            ],
        ),
    ]
