# Generated by Django 6.0.1 on 2026-02-06 15:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interventions', '0004_typeintervention'),
        ('ticket', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='type_demande',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='interventions.typeintervention'),
        ),
        migrations.DeleteModel(
            name='TypeDemande',
        ),
    ]
