# Generated by Django 6.0.1 on 2026-02-11 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0003_ticket_departement_ticket_priorite_ticket_technicien'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='statut',
            field=models.CharField(choices=[('ouvert', 'Ouvert'), ('en_cours', 'En_cours'), ('ferme', 'Fermé')], default='ouvert', max_length=25),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='titre',
            field=models.CharField(max_length=200),
        ),
    ]
